### ISSUE TITLE
Hello, is this the official implementation of the paper “Object Tracking and Geo-Localization from Street Images”?

### ISSUE THREAD

**Issue by LiuChong-911** [DevFreak-ui/gps_hunter#1]
Hello, is this the official implementation of the paper “Object Tracking and Geo-Localization from Street Images”? The source code URL https://gitlab.com/vail-uvm/VTrans-AI provided in the PDF of the paper seems to be invalid.

**Comment by DevFreak-ui** [comment]
Hi @LiuChong-911 ,

Unfortunately, this is not the official implementation of the paper. This repository is an attempt to implement the paper for educational purposes.

You can get in touch with one of the primary authors at daniel.wilson@uvm.edu

**Comment by LiuChong-911** [comment]
Copy that, many thanks for you reply!
